services:
  web_screen_app:
    env_file:
      - .env
    image: crpi-djclsl1v0hr7nb4m.cn-shenzhen.personal.cr.aliyuncs.com/dakar/web_screen:v0.8.9
    # image:       # for local test
    container_name: web_screen
    network_mode: "host"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./:/data
    command: python3 main.py
    init: true
